### ISSUE TITLE
Getting key already added error when using en-CA culture?

### ISSUE THREAD

**Issue by d-miles** [kappy/DateTimeExtensions#42]
I'm getting this error when I try to use a WorkingDayCultureInfo set to en-CA:

    An item with the same key has already been added.

I also get the same error on your test website:
http://datetimeextensions.azurewebsites.net/en-CA/Calendar/Index/2016

Any ideas?

**Comment by kappy** [comment]
Thanks. I have some clues on what can be going wrong there, maybe an observance of 2 holidays are being set on same day.

I'll have a look in it.

**Comment by kappy** [comment]
Fixed on 3.7.1.7. Should be already available on nuget
