### ISSUE TITLE
Change test time to "3:59:58" instead of "3:59:59"

### ISSUE THREAD

**Issue by tfreitasleal** [kappy/DateTimeExtensions#49]
The repeated value "59" could hide isssues.

**Comment by tfreitasleal** [comment]
Can be closed after merging PR #48

**Comment by kappy** [comment]
Done, but I didn't get the reason for this change

**Comment by tfreitasleal** [comment]
If both minutes and seconds are set to 59, you can't be sure whether the constuctor is handling minutes as minutes and seconds asseconds. Setting minutes and seconds to different values allows you to make really sure minutes are handled as minutes and seconds are handled as seconds.

**Comment by kappy** [comment]
Ah. Yes, that's seems a good point :+1:
