### ISSUE TITLE
Future .net core support

### ISSUE THREAD

**Issue by huhubun** [kappy/DateTimeExtensions#60]
Hi kappy, thanks for your great plugin. I am wondering if you have any plan to support .net core in the future?

**Comment by kappy** [comment]
Hi,
Yes I do plan it for version 4.0, but I can't rally tell when, or even how, right now.

**Comment by huhubun** [comment]
Oh, so cool!
Thank you

**Comment by kappy** [comment]
Hi,

Well, I took your lead, and make up some time to make it happen (amongst other things I also wanted to make).
You can get the alpha package from this feed: https://www.myget.org/feed/datetimeextensions/package/nuget/DateTimeExtensions

To try it out, just add to the Package Manager Settings on Visual Studio this api address: https://www.myget.org/F/datetimeextensions/api/v3/index.json

Can you give it a look and see if it works on you .net core project?

**Comment by huhubun** [comment]
Hi kappy,

I tried the version 4.0.0-alpha-0031, and it looks good to me.

Thanks  for letting me try those, i really appreciate it.
